trigger:
  batch: false
  branches:
    include:
      - master
  paths:
    include:
      - Microservices/ClearingHouseService/ClearingHouseService.Web/*
      - Microservices/Authentication/*
      - Microservices/BillingService/BillingService.Domain/*
      - Microservices/EdiFabric/EdiFabric.Templates/*
      - Microservices/Rethink.Services.Common/*
      - Microservices/Rethink.Services.Domain/*
    exclude: 
      - '**/*README.md'
      - '**/*.yaml'
      - '**/*.yml'
pr: none

parameters:
- name: env
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - prd
  - stg

resources:
 - repo: self  

variables:
   vmImageName: 'ubuntu-latest'
   dockerfilePath: '$(Build.SourcesDirectory)/Microservices/ClearingHouseService/ClearingHouseService.Web/Dockerfile' 
   TagBuild: 'rtabilling/clearinghouseserviceweb${{ parameters.env }}:$(Build.BuildNumber)'
   TagLatest: 'rtabilling/clearinghouseserviceweb${{ parameters.env }}:latest'
   ${{ if ne(parameters.env, 'prd') }}:
    container: $(devACR)
    login: $(devDockerLogin)
    password: $(devDockerPassword)
   ${{ else }}:
    container: $(ACR)
    login: $(DockerLogin)
    password: $(DockerPassword)
   ${{ if eq(parameters.env, 'dev') }}:
    Environment: 'development'
   ${{ if eq(parameters.env, 'qa') }}:
    Environment: 'qa'
   ${{ if eq(parameters.env, 'stg') }}:
    Environment: 'staging'
   ${{ if eq(parameters.env, 'prd') }}:
    Environment: 'production'
  
stages:
  - template: stage.build.yml