using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal;
using Rethink.Services.Common.Models.RethinkDataEntityClasses.Transaction;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Rethink.Services.Common.Infrastructure.Context
{
    [ExcludeFromCodeCoverage]
    public abstract class BaseDbContext<TContext> : DbContext where TContext : DbContext
    {
        private readonly string _connectionString;

        public DbSet<TransactionEntity> Transactions { get; set; }

        protected BaseDbContext(DbContextOptions<TContext> dbContextOptions)
        {
            _connectionString = dbContextOptions.FindExtension<SqlServerOptionsExtension>().ConnectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(_connectionString);
        }

        public void Commit()
        {
            var transactionEntries = OnBeforeSaveChanges();
            SaveChanges();
            OnAfterSaveChanges(transactionEntries);
        }
        public async Task CommitAsync(CancellationToken token = default)
        {
            var transactionEntries = OnBeforeSaveChanges();
            await SaveChangesAsync(token);
            await OnAfterSaveChangesAsync(transactionEntries);
        }

        public DbSet<TEntity> SetEntity<TEntity>() where TEntity : class
        {
            return Set<TEntity>();
        }

        public string GetTableName(DbContext context, Type entityType)
        {
            var entityModelType = context.Model.FindEntityType(entityType);
            var tableName = entityModelType.GetTableName();

            return tableName;
        }

        public DbConnection GetDbConnection()
        {
            return Database.GetDbConnection();
        }

        public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            return base.SaveChangesAsync(cancellationToken);
        }

        public override int SaveChanges()
        {
            return base.SaveChanges();
        }

        public abstract Task LogStoredProcedureParameters(string storedProcedureName, string parameters);

        #region Transaction feature
        private List<TransactionEntry> OnBeforeSaveChanges()
        {
            ChangeTracker.DetectChanges();

            var transactionEntries = new List<TransactionEntry>();

            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                {
                    continue;
                }

                if (entry.Entity is ITransactionEntity)
                {
                    ITransactionEntity transactionEntity = entry.Entity as ITransactionEntity;

                    var transactionEntry = new TransactionEntry(entry)
                    {
                        TableName = entry.Metadata.GetTableName(),
                        ReferenceId = transactionEntity.Id,
                        ReferenceTypeId = transactionEntity.EntityTypeId,
                        TypeId = transactionEntity.TypeId,
                        TransactionBy = transactionEntity.ModifiedBy ?? transactionEntity.CreatedBy// ?? transactionEntity.CreatedBy,
                    };

                    foreach (var property in entry.Properties)
                    {
                        if (property.IsTemporary)
                        {
                            // value will be generated by the database, get the value after saving
                            transactionEntry.TemporaryProperties.Add(property);
                            continue;
                        }

                        string propertyName = property.Metadata.Name;

                        if (property.OriginalValue == null && property.CurrentValue == null)
                        {
                            continue;
                        }

                        if (transactionEntity.PropertiesToExclude.Contains(propertyName))
                        {
                            continue;
                        }

                        switch (entry.State)
                        {
                            case EntityState.Added:
                                transactionEntry.NewValues[propertyName] = property.CurrentValue;
                                break;

                            case EntityState.Deleted:
                                transactionEntry.OldValues[propertyName] = property.OriginalValue;
                                break;

                            case EntityState.Modified:
                                if (property.IsModified && (property.OriginalValue == null || !property.OriginalValue.Equals(property.CurrentValue)))
                                {
                                    if (property.OriginalValue != property.CurrentValue)
                                    {
                                        transactionEntry.OldValues[propertyName] = property.OriginalValue;
                                        transactionEntry.NewValues[propertyName] = property.CurrentValue;
                                    }
                                }
                                break;
                        }
                    }

                    if (transactionEntry.NewValues.Count > 0 || transactionEntry.HasTemporaryProperties)
                    {
                        transactionEntries.Add(transactionEntry);
                    }
                }
            }

            // Save audit entities that have all the modifications
            foreach (var transactionEntry in transactionEntries.Where(_ => !_.HasTemporaryProperties))
            {
                Transactions.Add(transactionEntry.ToTransaction());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return transactionEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }

        private Task OnAfterSaveChangesAsync(List<TransactionEntry> transactionEntries)
        {
            if (transactionEntries == null || transactionEntries.Count == 0)
            {
                return Task.CompletedTask;
            }

            foreach (var transactionEntry in transactionEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in transactionEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        transactionEntry.ReferenceId = (int)prop.CurrentValue;
                    }
                    else
                    {
                        transactionEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                Transactions.Add(transactionEntry.ToTransaction());
            }

            return SaveChangesAsync();
        }

        private void OnAfterSaveChanges(List<TransactionEntry> transactionEntries)
        {
            if (transactionEntries == null || transactionEntries.Count == 0)
            {
                return;
            }

            foreach (var transactionEntry in transactionEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in transactionEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        transactionEntry.ReferenceId = (int)prop.CurrentValue;
                    }
                    else
                    {
                        transactionEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                Transactions.Add(transactionEntry.ToTransaction());
            }

            SaveChanges();
        }

        #endregion
    }
}