apiVersion: v1
kind: Secret
metadata:
  name: clearinghouse-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: clearinghouse-platform
type: Opaque
stringData:
  keyvault-uri: {{ .Values.keyVault.vaultUri | quote }}
  servicebus-connection: {{ .Values.serviceBus.connectionString | quote }}
  database-connection: {{ .Values.database.connectionString | quote }}
  appinsights-connection: {{ .Values.appInsights.connectionString | quote }}
