<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoginService.Domain\LoginService.Domain.csproj" />
    <ProjectReference Include="..\Rethink.Services.Common\Rethink.Services.Common.csproj" />
  </ItemGroup>

</Project>
