trigger:
  batch: false
  branches:
    include:
      - master
  paths:
    include:
      - billing_ui_app/*
    exclude: 
      - '**/*README.md'
      - '**/*.yaml'
      - '**/*.yml'

parameters:
- name: env
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - prd
  - stg
- name: subscription
  displayName: Subscription
  type: string
  default: dev/qa/stg
  values:
   - dev/qa/stg
   - prd

variables:
   TagBuild: 'rtabilling/rethinkbilling${{ parameters.env }}:$(Build.BuildNumber)'
   TagLatest: 'rtabilling/rethinkbilling${{ parameters.env }}:latest'
   ${{ if eq(parameters.subscription, 'prd') }}:
    AzureSubscription: 'b7f0e3aa-ffba-4489-af81-58ad0d94da4f'
    container: $(ACR)
    login: $(DockerLogin)
    password: $(DockerPassword)
   ${{ else }}:
    AzureSubscription: '716910cd-44da-48bc-a43b-bc01c1af0473'
    container: $(devACR)
    login: $(devDockerLogin)
    password: $(devDockerPassword)
   KendoLicense: $(KENDO_UI_LICENSE)
   ${{ if eq(parameters.env, 'dev') }}:
    Environment: 'development'
   ${{ if eq(parameters.env, 'qa') }}:
    Environment: 'qa'
   ${{ if eq(parameters.env, 'stg') }}:
    Environment: 'staging'
   ${{ if eq(parameters.env, 'prd') }}:
    Environment: 'production'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# - task: Checkmarx AST@2
#   inputs:
#     CheckmarxService: 'ChckMarxAzureDevOps'
#     projectName: '$(Build.Repository.Name)'
#     branchName: '$(Build.SourceBranchName)'
#     tenantName: 'RethinkFirst'
#     additionalParams: '--debug --async'

- task: AzureCLI@2
  displayName: Docker Build rethinkbilling
  inputs:
    scriptType: bash
    azureSubscription: $(AzureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      cd billing_ui_app
      rm -rf .angular/cache
      echo $(password) | docker login --username $(login) --password-stdin https://$(container)
      docker build --build-arg ENVIRONMENT=$(Environment) --build-arg KENDO_UI_LICENSE=$(KendoLicense) -t $(TagBuild) -t $(TagLatest) .
      docker run -d -p 4200:80 -t $(TagLatest)

- task: AzureCLI@2
  displayName: Docker Tag and Push rethinkbilling
  inputs:
    scriptType: bash
    azureSubscription: $(AzureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      docker image tag $(TagLatest) $(container)/$(TagLatest)
      docker image tag $(TagLatest) $(container)/$(TagBuild)
      docker image push $(container)/$(TagBuild)
      docker image push $(container)/$(TagLatest)