
SET NOEXEC OFF
SET NOCOUNT ON
SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
IF @@ERROR <> 0 SET NOEXEC ON
-- Rollback Inserted Record into ClaimStatus
BEGIN TRANSACTION;
    DELETE FROM ClaimStatus
    WHERE Id = 19
    AND Name = 'Submission Failed'
COMMIT TRANSACTION;
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
GO
COMMIT TRANSACTION
GO
DECLARE @Success AS BIT
SET @Success = 1
SET NOEXEC OFF
IF (@Success = 1)
    PRINT 'Rollback succeeded'
ELSE
BEGIN
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
    PRINT 'The rollback failed. ROLLBACK TRANSACTION'
END
GO