apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "billingservice.fullname" . }}-config
  labels:
    app.kubernetes.io/name: billingservice
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.environment | default "Production" | quote }}
  BillingService__Modernization__EnableCleanArchitectureAdapters: {{ .Values.modernization.enableCleanArchitectureAdapters | quote }}
  BillingService__Modernization__EnableDistributedCacheDecorators: {{ .Values.modernization.enableDistributedCacheDecorators | quote }}
  BillingService__Modernization__EnableOutboxPublisher: {{ .Values.modernization.enableOutboxPublisher | quote }}
  BillingService__Modernization__EnableReadModelQueries: {{ .Values.modernization.enableReadModelQueries | quote }}
