import { Gender, ClientStatus, ServiceIntensity } from '@core/enums/clients';
import { LocationFacility } from '@core/enums/location';
import { CustomField } from '../common';
import { Address } from './address';

export class Demographic {
    public id: number;
    public firstName: string;
    public middleName: string;
    public lastName: string;
    public dob: Date;
    public dobString: string;
    public gender: Gender;
    public address: string;
    public clientId: string;
    public uci: string;
    public clientOrder: string;
    public reasonForReferral: string;
    public hipaaNopAgreementDate: Date;
    public location: LocationFacility;
    public status: ClientStatus;
    public serviceIntensityTypeId: number;
    public serviceIntensityType: ServiceIntensity;
    public notes: string;
    public showClinical: boolean;
    public showScheduling: boolean;
    public showBilling: boolean;
    public dateDeleted: Date;
    public canChangeServiceIntensityType: boolean;
    public kareoPatientId: number;
    public customFields: CustomField[];
    public consentToAccess: boolean;
    public consentToAccessDate: Date;
    public consentToAccessString: string;
    public city: string;
    public town: string;
    public stateName: string;
    public zipCode: string;
    public countryName: string;
}
