apiVersion: v1
kind: ConfigMap
metadata:
  name: billingservice-app-config
  namespace: billingservice
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  BillingModernization__UseLegacyProxyFallback: "true"
  BillingModernization__ClaimHeadersMigrationMode: "Off"
  Telemetry__ServiceName: "billingservice-app"
  Telemetry__OtlpEndpoint: "http://otel-collector.monitoring:4317"
  LegacyBilling__BaseUrl: "http://billingservice-web.default.svc.cluster.local"

