apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: billingservice-app-api-hpa
  namespace: billingservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: billingservice-app-api
  minReplicas: 3
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

