apiVersion: v1
kind: Secret
metadata:
  name: billingservice-app-secrets
  namespace: billingservice
type: Opaque
stringData:
  ConnectionStrings__Database: "Server=tcp:billing-sql.database.windows.net,1433;Initial Catalog=BillingDb;Authentication=Active Directory Managed Identity;Encrypt=True;TrustServerCertificate=False;"
  ConnectionStrings__BillingOutbox: "Server=tcp:billing-sql.database.windows.net,1433;Initial Catalog=BillingDb;Authentication=Active Directory Managed Identity;Encrypt=True;TrustServerCertificate=False;"
  ConnectionStrings__Redis: "billing-redis.redis.cache.windows.net:6380,password=REPLACE_ME,ssl=True,abortConnect=False"
  ConnectionStrings__ServiceBus: "Endpoint=sb://REPLACE_ME.servicebus.windows.net/;SharedAccessKeyName=REPLACE_ME;SharedAccessKey=REPLACE_ME"

