FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./src ./src
RUN dotnet restore ./src/BillingService.Workers/BillingService.Workers.csproj
RUN dotnet publish ./src/BillingService.Workers/BillingService.Workers.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BillingService.App.Workers.dll"]

