parameters:
 - name: ContainerTestFolder
   type: string
 - name: DependsOn
   type: object
   default: []

stages:
 - stage: Build
   dependsOn: ${{ parameters.DependsOn }}
   jobs:
   - job: Build
     displayName: Build
     steps:
     - script: |
        pwd
        ls -lrt
        echo $(password) | docker login --username $(login) --password-stdin https://$(container)
        echo "Tag Build: $(TagBuild)"
        echo "Tag Latest: $(TagLatest)"
        docker build --no-cache --build-arg ENVIRONMENT=$(Environment) --build-arg ACCESS_TOKEN=$PAT -f $(dockerfilePath) -t $(TagBuild) -t $(TagLatest) .
        docker image tag $(TagBuild) $(container)/$(TagBuild)
        docker image tag $(TagBuild) $(container)/$(TagLatest)
        docker create -ti --name testcontainer $(TagBuild)
        docker cp testcontainer:${{parameters.ContainerTestFolder}} $(Build.ArtifactStagingDirectory)/testresults
        docker cp testcontainer:/app/coveragereport/ $(Build.ArtifactStagingDirectory)/coveragereport
       env:
        PAT: $(System.AccessToken)
       displayName: Build 

     - task: PublishCodeCoverageResults@1
       displayName: 'Publish Coverage'
       inputs:
         codeCoverageTool: Cobertura
         summaryFileLocation: '$(Build.ArtifactStagingDirectory)/coveragereport/Cobertura.xml'
         reportDirectory: '$(Build.ArtifactStagingDirectory)/coveragereport'

     - task: PublishTestResults@2
       displayName: Publish Tests
       inputs:
         testResultsFormat: 'VSTest'
         testResultsFiles: '**/*.trx'
         searchFolder: '$(Build.ArtifactStagingDirectory)/testresults'
         failTaskOnFailedTests: false
      
     - task: BuildQualityChecks@8
       displayName: 'Quality Check'
       inputs:
         checkCoverage: true
         coverageType: lines
         coverageFailOption: fixed
         coverageThreshold: 1
     
     - script: |
        docker push $(container)/$(TagBuild)
        docker push $(container)/$(TagLatest)
       displayName: Push to registry
    
     # - task: PublishPipelineArtifact@1
     #   inputs:
     #     artifactName: 'manifests'
     #     path: 'manifests'