apiVersion: v1
kind: Secret
metadata:
  name: billingservice-app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ConnectionStrings__Database: {{ .Values.secrets.ConnectionStrings__Database | quote }}
  ConnectionStrings__BillingOutbox: {{ .Values.secrets.ConnectionStrings__BillingOutbox | quote }}
  ConnectionStrings__Redis: {{ .Values.secrets.ConnectionStrings__Redis | quote }}
  ConnectionStrings__ServiceBus: {{ .Values.secrets.ConnectionStrings__ServiceBus | quote }}

