apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billingservice-web
  namespace: billing
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: billingservice
      app.kubernetes.io/component: api
